PROGRAM CAVITIES

! FIND CAVITIES IN A GIVEN CRYSTAL STRUCTURE
!
! - SAMPLE UNIT CELL AND INSERT MAXIMUM SIZED SPHERES
!   AT EACH GRID POINT
! - FIND LOCAL MAXIMA IN SPHERE RADII AND OUTPUT THESE

IMPLICIT NONE


DOUBLE PRECISION :: LATTICE,A(3,3),A1LEN,A2LEN,A3LEN,SPHPOS(3),NNDIST,DX,DY,DZ,RDIR(3),RDIST,RAD
INTEGER :: I,J,K,NGX,NGY,NGZ,IOUNIT,IOERR,NEXT,NTYPES,NIONS(10),NATOMS,AT
INTEGER :: I1,J1,K1,II,JJ,KK
LOGICAL :: SELDYN
CHARACTER :: COORDTYPE
INTEGER, ALLOCATABLE :: NIONS_TMP(:)
DOUBLE PRECISION, ALLOCATABLE :: POSATOM(:,:),SPHRAD(:,:,:)
LOGICAL, ALLOCATABLE :: MASK(:,:,:)

CHARACTER*80 :: SYSNAME,POSFILE
CHARACTER :: CDUMMY

WRITE(*,*) 'POSCAR-like FILE:'
READ(*,*) POSFILE

! GET INPUT DATA
IOUNIT=123
OPEN(IOUNIT,FILE=POSFILE)
READ(IOUNIT,*) SYSNAME
READ(IOUNIT,*) LATTICE
READ(IOUNIT,*) ((A(J,I),J=1,3),I=1,3)
! VASP5 assumed here:
READ(IOUNIT,*)
!!
DO NTYPES=1,10
  ALLOCATE(NIONS_TMP(NTYPES))
  NEXT=0
  REWIND IOUNIT
! VASP5 assumed here:
  DO I=1,6
    READ(IOUNIT,*)
  END DO
  READ(IOUNIT,*,IOSTAT=IOERR) (NIONS_TMP(I),I=1,NTYPES),NEXT
  IF (NEXT.EQ.0) GOTO 105
  DEALLOCATE(NIONS_TMP)
END DO
105 CONTINUE
BACKSPACE IOUNIT
NIONS=0
DO I=1,NTYPES
   NIONS(I)=NIONS_TMP(I)
ENDDO
SELDYN=.FALSE.
READ(IOUNIT,*) COORDTYPE
IF((COORDTYPE.EQ.'s').OR.(COORDTYPE.EQ.'S')) THEN
   SELDYN=.TRUE.
   READ(IOUNIT,*) COORDTYPE
ENDIF

NATOMS=SUM(NIONS)
WRITE(*,'((A),I4,(A),I4)') 'NTYPES: ',NTYPES,'NATOMS: ',NATOMS
ALLOCATE(POSATOM(3,NATOMS))

DO I=1,NATOMS
  READ(IOUNIT,*) (POSATOM(J,I),J=1,3)
ENDDO
CLOSE(IOUNIT)

! SET UP GRID AND GET NEAREST NEIGHBOUR FOR EACH POINT

A1LEN=LATTICE*SQRT(SUM(A(:,1)*A(:,1)))
A2LEN=LATTICE*SQRT(SUM(A(:,2)*A(:,2)))
A3LEN=LATTICE*SQRT(SUM(A(:,3)*A(:,3)))

NGX=INT(A1LEN*20)
NGY=INT(A2LEN*20)
NGZ=INT(A3LEN*20)
WRITE(*,*) 'USING THIS GRID TO SAMPLE THE UNIT CELL:'
write(*,*) NGX,NGY,NGZ

ALLOCATE(SPHRAD(NGZ,NGY,NGX))
ALLOCATE(MASK(NGZ,NGY,NGX))
SPHRAD=0.
MASK=.FALSE.

DO I=1,NGX
  SPHPOS(1)=REAL(I-1)/NGX
  DO J=1,NGY
    SPHPOS(2)=REAL(J-1)/NGY
    DO K=1,NGZ
      SPHPOS(3)=REAL(K-1)/NGZ
      NNDIST=1000.
      DO AT=1,NATOMS
        DX=MOD(SPHPOS(1)-POSATOM(1,AT)+2.5,1.0)-0.5
        DY=MOD(SPHPOS(2)-POSATOM(2,AT)+2.5,1.0)-0.5
        DZ=MOD(SPHPOS(3)-POSATOM(3,AT)+2.5,1.0)-0.5
        RDIR(1)=DX*A(1,1)+DY*A(1,2)+DZ*A(1,3)
        RDIR(2)=DX*A(2,1)+DY*A(2,2)+DZ*A(2,3)
        RDIR(3)=DX*A(3,1)+DY*A(3,2)+DZ*A(3,3)
        RDIST=LATTICE*SQRT(SUM(RDIR*RDIR))
        IF(RDIST.LT.NNDIST) NNDIST=RDIST
      ENDDO
      SPHRAD(K,J,I)=NNDIST
    ENDDO
  ENDDO
ENDDO

! FIND LOCAL MINIMA IN SPHERE RADII

WRITE(*,*) 'FRACTIONAL COORDINATES AND RADII OF SPHERES FOUND:'
DO I=1,NGX
  DO J=1,NGY
    DO K=1,NGZ
      RAD=SPHRAD(K,J,I)
!      MASK=.FALSE.
      DO I1=I-5,I+5
        II=MOD(I1+NGX,NGX)
        DO J1=J-5,J+5
          JJ=MOD(J1+NGY,NGY)
          DO K1=K-5,K+5
            KK=MOD(K1+NGZ,NGZ)
            IF(SPHRAD(KK,JJ,II).GT.RAD) GOTO 101
!            MASK(KK,JJ,II)=.TRUE.
          ENDDO
        ENDDO
      ENDDO
!      IF(MAXVAL(SPHRAD,MASK).EQ.RAD) WRITE(*,'(3F10.4,F12.8)') REAL(I-1)/NGX,REAL(J-1)/NGY,REAL(K-1)/NGZ,RAD
      WRITE(*,'(3F10.4,F12.8)') REAL(I-1)/NGX,REAL(J-1)/NGY,REAL(K-1)/NGZ,RAD
!      WRITE(*,*) I,J,K,RAD
101 CONTINUE
    ENDDO
  ENDDO
ENDDO

WRITE(*,*) 'MAXIMUM SPHERE RADIUS FOUND:'
write(*,*) maxval(sphrad)

END
